config/routes.rb
Rails.application.routes.draw do
  resources :moods do
    member do
      post 'add_song', to: 'moods#add_song'
      delete 'remove_song', to: 'moods#remove_song'
    end
  end
  resources :songs do
    member do
      delete 'remove_mood', to: 'songs#remove_mood'
    end
  end
  resources :users do
    member do
      post 'add_to_playlist', to: 'users#add_to_playlist'
      delete 'remove_from_playlist', to: 'users#remove_from_playlist'
      post 'add_mood', to: 'users#add_mood'
      delete 'remove_mood', to: 'users#remove_mood'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :song_moods
  has_many :songs, through: :song_moods
  has_many :user_moods
  has_many :users, through: :user_moods

  validates :name, presence: true, uniqueness: true
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: %i[ show edit update destroy add_song remove_song ]

  # GET /moods or /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1 or /moods/1.json
  def show
    @songs = @mood.songs
    @all_other_songs = Song.where.not(id: @songs.ids)
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods or /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to mood_url(@mood), notice: "Mood was successfully created." }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1 or /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to mood_url(@mood), notice: "Mood was successfully updated." }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_song
    SongMood.find_or_create_by(mood_id: @mood.id, song_id: params[:song_id])
    redirect_to @mood
  end

  def remove_song
    SongMood.find_by(mood_id: @mood.id, song_id: params[:song_id])&.delete
    redirect_to @mood
  end

  # DELETE /moods/1 or /moods/1.json
  def destroy
    @mood.destroy

    respond_to do |format|
      format.html { redirect_to moods_url, notice: "Mood was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mood_params
      params.require(:mood).permit(:name)
    end
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/moods/_form.html.erb
<%= form_with(model: mood, local: true) do |form| %>
  <% if mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
        <% mood.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Show', @mood %> |
<%= link_to 'Back', moods_path %>

app/views/moods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @moods.each do |mood| %>
      <tr>
        <td><%= mood.name %></td>
        <td><%= link_to 'Show', mood %></td>
        <td><%= link_to 'Edit', edit_mood_path(mood) %></td>
        <td><%= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mood', new_mood_path %>

<%= link_to 'Users', users_path %>
<%= link_to 'Songs', songs_path %>

app/views/moods/new.html.erb
<h1>New Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Back', moods_path %>

app/views/moods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mood.name %>
</p>

<%= link_to 'Edit', edit_mood_path(@mood) %> |

<br>
<br>
<br>
<hr>
<br>

<% if @songs.count.positive? %>
  <h1>Songs Under Mood</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Genre</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
        <tr>
          <td><%= song.title %></td>
          <td><%= song.artist %></td>
          <td><%= song.genre %></td>
          <td><%= link_to 'Goto Song', song %></td>
          <td><%= link_to 'Remove from Mood', remove_song_mood_path(song_id: song.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No Songs Is Added In This Mood</h1>
<% end %>

<br>
<br>
<br>
<hr>
<br>

<% if @all_other_songs.count.positive? %>
  <h1>Songs That Are Not Added In This Mood</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Genre</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @all_other_songs.each do |song| %>
        <tr>
          <td><%= song.title %></td>
          <td><%= song.artist %></td>
          <td><%= song.genre %></td>
          <td><%= link_to 'Goto Song', song %></td>
          <td><%= link_to 'Add to mood', add_song_mood_path(song_id: song.id), method: :post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>All Songs Added To This Mood</h1>
<% end %>

<%= link_to 'Moods', moods_path %>
<%= link_to 'Users', users_path %>
<%= link_to 'Songs', songs_path %>