config/routes.rb
Rails.application.routes.draw do
  resources :moods do
    member do
      post 'add_song', to: 'moods#add_song'
      delete 'remove_song', to: 'moods#remove_song'
    end
  end
  resources :songs do
    member do
      delete 'remove_mood', to: 'songs#remove_mood'
    end
  end
  resources :users do
    member do
      post 'add_to_playlist', to: 'users#add_to_playlist'
      delete 'remove_from_playlist', to: 'users#remove_from_playlist'
      post 'add_mood', to: 'users#add_mood'
      delete 'remove_mood', to: 'users#remove_mood'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_songs
  has_many :songs, through: :user_songs
  has_many :user_moods
  has_many :moods, through: :user_moods

  validates :name, :email, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy add_to_playlist remove_from_playlist add_mood remove_mood mood_wise_song_randomizer ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @songs = @user.songs
    @moods = @user.moods
    @all_other_songs = Song.where.not(id: @songs.ids)
    @all_other_moods = Mood.where.not(id: @moods.ids)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_to_playlist
    UserSong.find_or_create_by(user_id: @user.id, song_id: params[:song_id])
    redirect_to @user
  end

  def remove_from_playlist
    UserSong.find_by(user_id: @user.id, song_id: params[:song_id])&.delete
    redirect_to @user
  end

  def add_mood
    UserMood.find_or_create_by(user_id: @user.id, mood_id: params[:mood_id])
    redirect_to @user
  end

  def remove_mood
    UserMood.find_by(user_id: @user.id, mood_id: params[:mood_id])&.delete
    redirect_to @user
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<%= link_to 'Moods', moods_path %>
<%= link_to 'Songs', songs_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>

<br>
<br>
<br>
<hr>
<br>

<% if @songs.count.positive? %>
  <h1>My Playlist</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Genre</th>
        <th>Mood</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
        <tr>
          <td><%= song.title %></td>
          <td><%= song.artist %></td>
          <td><%= song.genre %></td>
          <td><%= song.moods.map(&:name).join(', ') %></td>
          <td><%= link_to 'Goto Song', song %></td>
          <td><%= link_to 'Remove from Playlist', remove_from_playlist_user_path(song_id: song.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No Songs Added To Playlist</h1>
<% end %>

<br>
<br>
<br>
<hr>
<br>

<% if @all_other_songs.count.positive? %>
  <h1>All Other Songs</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Genre</th>
        <th>Mood</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @all_other_songs.each do |song| %>
        <tr>
          <td><%= song.title %></td>
          <td><%= song.artist %></td>
          <td><%= song.genre %></td>
          <td><%= song.moods.map(&:name).join(', ') %></td>
          <td><%= link_to 'Goto Song', song %></td>
          <td><%= link_to 'Add to Playlist', add_to_playlist_user_path(song_id: song.id), method: :post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>All Songs Added To Playlist</h1>
<% end %>

<br>
<br>
<br>
<hr>
<br>

<% if @moods.count.positive? %>
  <h1>Moods Selected By User</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @moods.each do |mood| %>
        <tr>
          <td><%= mood.name %></td>
          <td><%= link_to 'Goto Mood', mood %></td>
          <td><%= link_to 'Remove Mood', remove_mood_user_path(mood_id: mood.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No Moods Selected By User</h1>
<% end %>

<br>
<br>
<br>
<hr>
<br>

<% if @all_other_moods.count.positive? %>
  <h1>Other Than Selected Moods</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @all_other_moods.each do |mood| %>
        <tr>
          <td><%= mood.name %></td>
          <td><%= link_to 'Goto Mood', mood %></td>
          <td><%= link_to 'Add Mood', add_mood_user_path(mood_id: mood.id), method: :post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No Moods Selected By User</h1>
<% end %>

<%= link_to 'Users', users_path %>
<%= link_to 'Moods', moods_path %>
<%= link_to 'Songs', songs_path %>