config/routes.rb
Rails.application.routes.draw do
  resources :moods do
    member do
      post 'add_song', to: 'moods#add_song'
      delete 'remove_song', to: 'moods#remove_song'
    end
  end
  resources :songs do
    member do
      delete 'remove_mood', to: 'songs#remove_mood'
    end
  end
  resources :users do
    member do
      post 'add_to_playlist', to: 'users#add_to_playlist'
      delete 'remove_from_playlist', to: 'users#remove_from_playlist'
      post 'add_mood', to: 'users#add_mood'
      delete 'remove_mood', to: 'users#remove_mood'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :user_songs
  has_many :users, through: :user_songs
  has_many :song_moods
  has_many :moods, through: :song_moods

  validates :title, :artist, :genre, presence: true
  validates :title, uniqueness: { scope: :artist }
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy remove_mood ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
    @moods = @song.moods
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        params[:song][:moods].each do |id|
          @song.song_moods.find_or_create_by(mood_id: id)
        end
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        params[:song][:moods].each do |id|
          @song.song_moods.find_or_create_by(mood_id: id)
        end
        @song.song_moods.where.not(mood_id: params[:song][:moods]).delete_all
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_mood
    SongMood.find_by(song_id: @song.id, mood_id: params[:mood_id])&.delete
    redirect_to @song
  end
  
  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :artist, :genre)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :moods %>
    <%= form.select :moods, options_from_collection_for_select(Mood.all, :id, :name, song.mood_ids), { include_blank: 'Please Select Single/Multiple Moods', include_hidden: false }, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Genre</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
        <td><%= song.genre %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

<%= link_to 'Moods', moods_path %>
<%= link_to 'Users', users_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |

<br>
<br>
<br>
<hr>
<br>

<h1>This Song Fall Under Moods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @moods.each do |mood| %>
      <tr>
        <td><%= mood.name %></td>
        <td><%= link_to 'Goto Mood', mood %></td>
        <td><%= link_to 'Remove', remove_mood_song_path(mood_id: mood.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Songs', songs_path %>
<%= link_to 'Moods', moods_path %>
<%= link_to 'Users', users_path %>